version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: db_note
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    build:
      context: .
    container_name: fastapi_app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: postgres
    ports:
      - 9999:8000
    depends_on:
      - db